# Dockerfile for the Seurat 4.3.0
FROM satijalab/seurat:4.3.0

RUN apt-get -y update \
      && apt-get -y dist-upgrade \
      && apt-get -y install --no-install-recommends --no-install-suggests \
        apt-transport-https apt-utils ca-certificates cmake curl g++ gcc \
        gfortran git make libblas-dev libcurl4-gnutls-dev libfontconfig1-dev \
        libfreetype6-dev libfribidi-dev libgit2-dev libharfbuzz-dev \
        libiodbc2-dev libjpeg-dev liblapack-dev libmariadb-dev libpng-dev \
        libpq-dev libsqlite3-dev libssh-dev libssl-dev libtiff5-dev \
        libxml2-dev locales pandoc pkg-config r-base libcairo2-dev libxt-dev \
      && apt-get -y autoremove \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*

#install specific versions of R packages
RUN R -e 'install.packages("remotes")'
RUN R -e "library('remotes');install_version('ggplot2', '3.4.1')"
RUN R -e "library('remotes');install_version('dplyr', '1.1.0')"
RUN R -e "library('remotes');install_version('gdata', '2.18.0.1')"
RUN R -e "library('remotes');install_version('harmony', '0.1.1')"
RUN R -e "library('remotes');install_version('gplots', '3.1.3')"
RUN R -e "library('remotes');install_version('RColorBrewer', '1.1-3')"
RUN R -e "library('remotes');install_version('ranger', '0.14.1')"
RUN R -e "library('remotes');install_version('foreach', '1.5.2')"
RUN R -e "library('remotes');install_version('doParallel', '1.0.17')"
RUN R -e "library('remotes');install_version('optparse', '1.7.3')"
RUN R -e "library('remotes');install_version('tidyverse', '2.0.0', dependencies = TRUE)"
RUN R -e "library('remotes');install_version('ggpubr', '0.6.0')"
RUN R -e "library('remotes');install_version('rliger', '1.0.0')"
RUN R -e 'install.packages("BiocManager")'
RUN R -e 'BiocManager::install(version = "3.14",ask = FALSE)'
RUN R -e 'BiocManager::install("glmGamPoi", version = "3.14")'
RUN R -e 'BiocManager::install(c("ComplexHeatmap", "dittoSeq", "DropletUtils", "Nebulosa"), version = "3.14")'
RUN R -e "library('remotes');install_version('scCustomize', '1.1.1', dependencies = TRUE)"
